export const mockEvents = [
    {
      id: "evt1",
      brideName: "Priya Sharma",
      groomName: "Aditya Patel",
      eventDate: "2024-04-15",
      totalAmount: 285000,
      contributionsCount: 24,
    },
    {
      id: "evt2",
      brideName: "Meera Reddy",
      groomName: "Arjun Kumar",
      eventDate: "2024-03-28",
      totalAmount: 156000,
      contributionsCount: 18,
    },
    {
      id: "evt3",
      brideName: "Ananya Singh",
      groomName: "Rohan Verma",
      eventDate: "2024-05-02",
      totalAmount: 342000,
      contributionsCount: 31,
    },
  ];
  
  export const mockContributions = {
    evt1: [
      {
        id: "cont1",
        name: "Rajesh & Sunita Gupta",
        amount: 51000,
        message: "Congratulations to the beautiful couple! Wishing you a lifetime of happiness.",
        date: "2024-04-15",
        relation: "bride" as const,
      },
      {
        id: "cont2",
        name: "Amit Shah",
        amount: 21000,
        message: "May your love grow stronger with each passing day!",
        date: "2024-04-15",
        relation: "groom" as const,
      },
      {
        id: "cont3",
        name: "Neha & Vikram Malhotra",
        amount: 31000,
        message: "Best wishes for a wonderful journey ahead!",
        date: "2024-04-15",
        relation: "bride" as const,
      },
      {
        id: "cont4",
        name: "Suresh Kumar",
        amount: 11000,
        message: "Blessings to the lovely couple!",
        date: "2024-04-14",
        relation: "groom" as const,
      },
      {
        id: "cont5",
        name: "Priyanka & Deepak Verma",
        amount: 25000,
        message: "Wishing you both a very happy married life!",
        date: "2024-04-14",
        relation: "bride" as const,
      },
    ],
    evt2: [
      {
        id: "cont6",
        name: "Ravi & Anjali Mehta",
        amount: 21000,
        message: "May your life be filled with joy and prosperity!",
        date: "2024-03-28",
        relation: "groom" as const,
      },
      {
        id: "cont7",
        name: "Sanjay Kapoor",
        amount: 15000,
        message: "Congratulations and best wishes!",
        date: "2024-03-28",
        relation: "bride" as const,
      },
      {
        id: "cont8",
        name: "Kavita & Rahul Sharma",
        amount: 31000,
        message: "Wishing you both a beautiful journey together!",
        date: "2024-03-27",
        relation: "groom" as const,
      },
    ],
    evt3: [
      {
        id: "cont9",
        name: "Arun & Meena Patel",
        amount: 51000,
        message: "Heartiest congratulations to the wonderful couple!",
        date: "2024-05-02",
        relation: "bride" as const,
      },
      {
        id: "cont10",
        name: "Kiran Reddy",
        amount: 25000,
        message: "May your love story continue forever!",
        date: "2024-05-02",
        relation: "groom" as const,
      },
      {
        id: "cont11",
        name: "Shweta & Nikhil Joshi",
        amount: 41000,
        message: "Wishing you a lifetime of love and happiness!",
        date: "2024-05-01",
        relation: "bride" as const,
      },
  ],
};
